### ISSUE TITLE
be aware of "hidden linebreaks/spaces"

### ISSUE THREAD

**Issue by benzkji** [aldryn/aldryn-search#57] opened 2015-12-16 13:43 UTC
Having this rendered by my plugin:

    <h1>The Title</h1>What

The word "The" and "TitleWhat" ends in my index. Maybe think about using strip_tags from django?

http://stackoverflow.com/questions/12824899/strip-tags-replace-tags-by-space-rather-than-deleting-them Everybody suggests regexes, but maybe lxml can do it?

**Comment by czpython** [comment] 2015-12-16 13:54
@benzkji Thanks.
We used to use a version of strip tags from django that took care of this but had to switch to lxml because django's was not able to strip js tags correctly, so it's possible that this is a regression from the switch.
Will investigate further.

**Comment by czpython** [comment] 2015-12-26 00:53
Fixed by ef4479f3cc532523168e61dca5cac95d9854cf80

**Closed by czpython** 2015-12-26 00:53 UTC
